---
version: '3.1'
services:
  app:
    build: .
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    depends_on:
      - pg_db

  pg_db:
    image: postgres:11.4
    hostname: postgresql
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres

  pg_admin:
    image: dpage/pgadmin4
    ports:
      - 9080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin